name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Executar Testes
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          cd /home/dennis/super-duper-octo-broccoli
          pip install -r requirements.txt

      - name: Executar testes com pytest
        run: |
          cd /home/dennis/super-duper-octo-broccoli
          pytest

  deploy:
    name: Deploy da aplicação
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Realizar deploy
        run: |
          cd /home/dennis/super-duper-octo-broccoli
          git pull
